= HDFS Connector Release Notes
:keywords: release notes, connectors, hdfs

The Anypoint Connector for the Hadoop Distributed File System (HDFS) is used as a bi-directional gateway between Mule applications and HDFS.

+See the link:/mule-user-guide/v/4.0/hdfs-connector[HDFS Connector User Guide].

== Version 6.0.0 - September 28, 2017

=== Version 6.0.0 Compatibility

[%header,width="100%", cols=","]
|===
|Software |Version
|Mule Runtime | 4.0 and higher
|Hadoop Distribute File System | 2.8.1 or higher
|===
=== Migrating from Older Versions

*Not applicable

=== Features

*Not applicable


=== Version 6.0.0 Fixed in this Release

*Not applicable


=== Version 6.0.0 Known Issues

*There are no known issues in this version

=== See also

Learn how to Install Anypoint Connectors using Anypoint Exchange.

Access MuleSoft’s Forum to pose questions and get help from Mule’?s broad community of users.

To access MuleSoft’s expert support team, subscribe to Mule ESB Enterprise and log into MuleSoft’s Customer Portal.
